### ISSUE TITLE
setting-huey-to-use-redis-with-flask on windows

### ISSUE THREAD

**Issue by kc1** [pjcunningham/flask-huey-example#1]
Hi , I've wrirren this:

https://stackoverflow.com/questions/51688505/setting-huey-to-use-redis-with-flask

would you mind taking a look?

**Comment by pjcunningham** [comment]
I've updated the [Readme](https://github.com/pjcunningham/flask-huey-example/blob/master/readme.md) with instructions on how to run Example 1.
